### ISSUE TITLE
Song plays for just 30 secs

### ISSUE THREAD

**Issue by itzmysteryy** [seeker710/music-youtube#1]
The project is very good but the song plays for just 30 secs, please fix it to play the whole song

**Comment by seeker710** [comment]
@itzmysteryy the api I am currently using provides only song preview. That's why songs are playing for 30 seconds only.
For more information about the api: [https://rapidapi.com/Glavier/api/spotify23/](https://rapidapi.com/Glavier/api/spotify23/)
